### ISSUE TITLE
Rust mode

### ISSUE THREAD

**Issue by ignacio-ca** [davidshepherd7/electric-operator#32] opened 2016-03-08 19:25 UTC
Is Rust unsupported? I tried and seem to add space only for comma in rust-mode.

**Comment by davidshepherd7** [comment] 2016-03-08 20:54
There's no explicit support but it should get some sensible defaults automatically. It looks like `rust-mode` doesn't  derive from `prog-mode` so it doesn't get them. I've [opened an issue on `rust-mode`](https://github.com/rust-lang/rust-mode/issues/139) so hopefully it should be sorted soon.

For now [this](http://emacs.stackexchange.com/a/7357/237) answer seems to fix the issue.

**Comment by davidshepherd7** [comment] 2016-03-08 21:08
From a quick glance at the rust docs it looks like supporting all of the syntax will be "interesting", but I'll have a look.

**Comment by ignacio-ca** [comment] 2016-03-08 22:23
Thanks, my elisp knowledge is limited, I have tried but couldn't make it work.

**Comment by davidshepherd7** [comment] 2016-03-08 23:21
Ok I just pushed some basic rust tweaks. 

I just disabled `*`, `&`, `<` and `>` because they have multiple meanings and there doesn't seem to be a way to detect what they represent short of writing half a rust compiler.

Let me know if there are any other things that need tweaking.

**Comment by ignacio-ca** [comment] 2016-03-09 15:04
If I realize something useful I let you know, but I still I could not get rust-mode to be aware of electric-mode.

**Comment by davidshepherd7** [comment] 2016-03-10 08:21
Which versions of rust-mode, electric-operator, and emacs are you using? With the latest version of electric-operator from melpa-unstable it should just work.

**Comment by ignacio-ca** [comment] 2016-03-11 01:59
I just upgraded electric-operator and now works. Great! I use emacs 24.5.1 and the last version of rust-mode and electric-operator.

**Comment by ignacio-ca** [comment] 2016-03-11 02:00
Should I close this issue?

**Comment by davidshepherd7** [comment] 2016-03-11 07:25
Yeah closing it is fine if the problem is solved :+1:.

Let me know if anything other than `<>&*` doesn't work as expected.

**Closed by davidshepherd7** 2016-03-11 07:25 UTC

**Comment by ignacio-ca** [comment] 2016-03-12 02:08
Ok!
