### ISSUE TITLE
problem with yasnippet

### ISSUE THREAD

**Issue by Dickby** [davidshepherd7/electric-operator#68] opened 2018-06-30 15:14 UTC
electric-operator-mode breaks yasnippet for example if i want to insert a for loop snippet that should look like this after filled in the fields
```
for(char *c = string; *c; ++c)
{
}
```
as soon as i type the first `*` electric-operator mode steps in, and yasnippet deactivates that snippet.

**Comment by davidshepherd7** [comment] 2018-07-03 19:35
Hi, thanks for reporting this. I use yasnippet too and I don't normally
have problems like this so I guess it's only broken in some specific
case(s).

What version of yasnippet are you using? Can you give me some exact
snippet(s) you'se having trouble with? Do you see this in all modes or just
C?

**Comment by Dickby** [comment] 2018-07-03 21:02
I use yasnippet from melpa(not stable).
Most of the time i program in c or c++, i just tried it in emacs-lisp-mode, and i get the same result.
if i type anything in a open yasnippet field that gets modified by electric-operator-mode, yasnippet just exits that snippet and i have to clear and fill the remaining fields manually.

**Comment by davidshepherd7** [comment] 2018-07-03 22:04
Hmm, I can't seem to reproduce it. Can you reproduce it in `emacs -Q`?

What are the exact version numbers of yasnippet and electric operator (you can find this e.g. by checking the number in the filename in the help for one of their functions)?

**Comment by Dickby** [comment] 2018-07-04 00:52
Yes:
1. start with `emacs -Q`
2. `M-x package-initialize`
3. `M-x yas-minor-mode`
4. `M-x electric-operator-mode`
5. `M-x emacs-lisp-mode`
6. `M-x yas-insert-snippet` return `defun` return
7. type `something*somthing_else`

and the opened yasnippet is inactive, at least in my case.
I use:
GNU Emacs 27.0.50
yasnippet-20180620.1750
electric-operator-20180627.1012

**Comment by davidshepherd7** [comment] 2018-07-10 11:00
Ok I've managed to reproduce it: it's a problem that only exists in the current master branch of emacs. Since it's not in any kind of pre-release yet I expect it's a bug (or breaking change) in emacs itself. 

I don't think I can really spend the time to support unreleased versions, so I'll leave this until the underlying cause is either released or fixed, sorry.

**Comment by Dickby** [comment] 2018-07-10 11:48
Thanks for the response.
For now i disable/enable it in yasnippet hooks.

**Comment by davidshepherd7** [comment] 2018-08-26 16:28
Closing for now, but if this is still an issue in a released version of emacs please reopen.

**Closed by davidshepherd7** 2018-08-26 16:28 UTC
Labels: wontfix
