### ISSUE TITLE
slash (/) within signle qoutation marks ('')

### ISSUE THREAD

**Issue by feng-li** [davidshepherd7/electric-operator#92] opened 2019-10-27 02:20 UTC
Currently `electric-operator` treats `/` as division  sign in single quotation marks (no problem with double quotation marks). This causes side effects when e.g. the input is a Linux path. 

 ```sh
path='code/python/init.py'
```
will be formatted as 

 ```sh
path = 'code / python / init.py'
```
 
I have noticed this affects both R and Python. Maybe could be handled in a better way or at least let it behave consistently with both single quotation marks and double quotation marks.

Thanks!

**Comment by davidshepherd7** [comment] 2019-10-28 08:48
Hi, I can't reproduce this in a normal python buffer. Can you please fill out the [issue template](https://github.com/davidshepherd7/electric-operator/blob/master/ISSUE_TEMPLATE.md) so that I know how to do so?

Is this only in python/R repl buffers? If so then see #87, it's because of a bug in emacs itself.

**Comment by davidshepherd7** [comment] 2020-04-10 09:34
Closing this because I think it's a duplicate of #87

**Closed by davidshepherd7** 2020-04-10 09:34 UTC
